# Generated by Django 5.2.3 on 2025-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=80)),
                ('datetime', models.DateTimeField()),
                ('department', models.CharField(max_length=80)),
                ('doctor', models.CharField(max_length=80)),
                ('message', models.TextField()),
            ],
        ),
    ]
